### ISSUE TITLE
Websocket over http sample error

### ISSUE THREAD

**Issue by jscuesta** [fanout/node-grip#2]
Hi, on https://github.com/fanout/node-grip/blob/master/samples/websocket-over-http.js make a require to 'gripcontrol' but it is not avaiable . Maybe it is a typo issue an is require('grip') ?

Regards,

**Comment by kbokarius** [comment]
Yep you are correct. We are fixing it now.

 

Thanks,

Kon

**Comment by kbokarius** [comment]
Fixed in c2dacba2896f5dcd2bf96fdc4aed713611eb393b
