### ISSUE TITLE
Grip Installation

### ISSUE THREAD

**Issue by Poolchaos** [fanout/node-grip#3]
I'm having an issue with the buffertools dependency, which is keeping me from being able to install grip.

I'm seeing: 

```
npm ERR! buffertools@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.6 install script.
```

**Comment by jkarneges** [comment]
Hmm, maybe a Node version issue? Installs okay for me with Node 6.12.3 and NPM 3.10.10.

**Comment by Poolchaos** [comment]
Will have a look, thanks

**Comment by jkarneges** [comment]
The latest version removes the buffertools dependency.
