### ISSUE TITLE
grip not running on lambda

### ISSUE THREAD

**Issue by tflack** [fanout/node-grip#4]
Despite all the instructions about being able to use lambda I'm not able to include grip in node modules because of it's dependency on buffertools. Since I can't run a native npm install in lambda node_modules includes the version built on my Mac which doesn't work.

Am I missing something? How are people able to get this working in Lambda?

**Comment by jkarneges** [comment]
I believe the key is to build the node_modules on a Linux machine. That's what I did when testing the library.

There's also this: https://github.com/tomdale/lambda-packager

**Comment by jkarneges** [comment]
And now the buffertools dependency has been removed! Hopefully this problem is gone.
